---
- hosts: all
  become: true
  tasks:
  - name: install chrony
    yum:
      name: chrony
      state: latest
      update_cache: yes
  - name: Restart chronyd
    service:
      name: chronyd
      state: restarted
